### PR TITLE
Support Plane primitives in the usd procedural

### LINKED ISSUE #2058: Support Plane primitives in the procedural
It looks like support for Plane primitives was never added to our USD translators. In hydra this would be automatically converted to a mesh

### PR DESCRIPTION
**Pull request by sebastienblor**
**Changes proposed in this pull request**
Adding a translator reader for UsdPlane primitives, using as a reference the code from UsdImaging planes https://github.com/PixarAnimationStudios/OpenUSD/blob/release/pxr/usdImaging/usdImaging/implicitSurfaceMeshUtils.cpp#L438

Adding test_2058 with such a prim, that was already passing in hydra, and that now passes in USD too

**Issues fixed in this pull request**
Fixes #2058

### CODE REVIEW

**Review by cpichard — COMMENTED** [review]
the CI is failing, it looks like 21.08 didn't have planes implemented
`libs/translator/reader/read_geometry.cpp:25:10: fatal error: 'pxr/usd/usdGeom/plane.h' file not found`

**Comment by sebastienblor** [comment]
ha, I wondered why we hadn't implemented them in the first place...

**Comment by cpichard** [comment]
It was added in 22.08 https://github.com/PixarAnimationStudios/OpenUSD/blob/release/CHANGELOG.md

**Comment by sebastienblor** [comment]
Added some ifdefs

**Review by cpichard — APPROVED** [review]

**Comment by sebastienblor** [comment]
Note that I removed here a duplicated line in the changelog

**Pull request merged**
