### PR TITLE
Initial support for USD 21.05 (specifically light token name changes)

### LINKED ISSUE #765: Can't compile when using USD 21.05
At present, it's not possible to compile when using USD 21.05 due to several issues:
- names of several light tokens have changed which breaks `render_delegate/light.cpp`
- changed signature of `UsdImagingGprimAdapter::Get` breaks compiling `UsdImagingArnoldShapeAdapter`
- removal of `_GetMaterialNetworkSelector` from `UsdImagingPrimAdapter`

### PR DESCRIPTION
**Pull request by robpieke**
**Changes proposed in this pull request**
- Conditionally using the new USD 21.05 light token names
- Tested (for compilation success) against USD 21.05, 21.02, 20.08

Related to #765

### CODE REVIEW

**Comment by sirpalee** [comment]
Hi Rob! I updated the description so it won't close #765, as there are more issues than just the light tokens in the render delegate.

**Review by sirpalee — APPROVED** [review]
Looks good, thanks for the PR!

**Comment by kikou** [comment]
Hi @robpieke, per legal requirements, you need to have the [individual CLA](docs/cla/Arnold%20components%20for%20USD%20-%20Ind%20Contrib%20Agmt.pdf) or [corporate CLA](docs/cla/Arnold%20components%20for%20USD%20-%20Corp%20Contrib%20Agmt.pdf) signed and returned to <arnold-usd.contributor.agreements@autodesk.com> before we can accept your pull requests.

**Comment by robpieke** [comment]
> Hi @robpieke, per legal requirements, you need to have the [individual CLA](docs/cla/Arnold%20components%20for%20USD%20-%20Ind%20Contrib%20Agmt.pdf) or [corporate CLA](docs/cla/Arnold%20components%20for%20USD%20-%20Corp%20Contrib%20Agmt.pdf) signed and returned to [arnold-usd.contributor.agreements@autodesk.com](mailto:arnold-usd.contributor.agreements@autodesk.com) before we can accept your pull requests.

Done!

**Comment by kikou** [comment]
@robpieke We have received your _individual_ CLA, thanks. However your updated PR now conflicts.

**Review by sirpalee — APPROVED** [review]

**Review by kikou — COMMENTED** [review]
LGTM

**Pull request merged**
