### PR TITLE
Migrate SCons build scripts to Python 3

### PR DESCRIPTION
**Pull request by ansono**
This PR will introduce the needed changes for using Python 3 for running the SCons build system.

This is is still compatible with Python 2 and uses SCons 3.1.2

### CODE REVIEW

**Comment by ansono** [comment]
The work in the PR includes:
- Minor polishing of the `abuild` scripts
- Port Python code to Python 3. That was simply `.iteritems()` to `.items()` in `dicts` and invalid `.has_key()` in `dict`s
- Update the custom MSCommon SCons tools to fully support VS2022

**Comment by cpichard** [comment]
Hi @ansono , I am testing with python 3.10.10 on macos arm64, and I have an error when running abuild:
```
 ./abuild build
./abuild: line 7: -B: command not found
./abuild: line 10: --site-dir=/Users/picharc/develop/ansono/arnold-usd/tools/scons-custom: No such file or directory
```

**Comment by ansono** [comment]
@cpichard , I fixed it in https://github.com/Autodesk/arnold-usd/pull/1505/commits/9b3aea28b0c960d61bef03393fd0e57827979e23. Could you try again?

**Comment by cpichard** [comment]
got a new error:
```
/opt/local/bin/python: can't open file '/Users/picharc/develop/ansono/arnold-usd/%SCONS_PATH%': [Errno 2] No such file or directory
```

**Comment by ansono** [comment]
> got a new error:
> 
> ```
> /opt/local/bin/python: can't open file '/Users/picharc/develop/ansono/arnold-usd/%SCONS_PATH%': [Errno 2] No such file or directory
> ```

Damn! sorry I used the windows notation for env vars ... hopefully fixed after https://github.com/Autodesk/arnold-usd/pull/1505/commits/21b9f6d26ea7c8ffc8475ffb748e1290f082f60f

**Comment by cpichard** [comment]
new one: 
```
ADSKMXQQT7TCQJ:arnold-usd picharc$ ./abuild build
scons: Reading SConscript files ...
ModuleNotFoundError: No module named 'build_tools':
  File "/Users/picharc/develop/ansono/arnold-usd/SConstruct", line 26:
    from utils import system, configure
  File "/Users/picharc/develop/ansono/arnold-usd/tools/utils/__init__.py", line 14:
    from . import build_tools, color, compiler, configure, dependencies, elf, git, \
  File "/Users/picharc/develop/ansono/arnold-usd/tools/utils/configure.py", line 16:
    from build_tools import convert_usd_version_to_int
```
strangely the build_tools.py is in the tools/utils folder

**Comment by ansono** [comment]
> new one:
> 
> ```
> ModuleNotFoundError: No module named 'build_tools':
> ```

That was fixed too in https://github.com/Autodesk/arnold-usd/pull/1505/commits/86e16429c9e04d0eba746a1ab94fb4e61e818c98

**Comment by ansono** [comment]
> Hi @ansono , with the latest version I have this issue :
> 
> ```
> ADSKMXQQT7TCQJ:arnold-usd picharc$ ./abuild build
> scons: Reading SConscript files ...
> 
> scons: *** Directory path for option ARNOLD_API_INCLUDES does not exist: /include
> File "/Users/picharc/develop/ansono/arnold-usd/SConstruct", line 131, in <module>
> ```
> 
> Is that something I need to add somewhere ?

I guess you need to point to a valid arnold path. I tested this building arnold-usd from arnold-core and arnold-mtoa.

**Comment by cpichard** [comment]
it looks like the my arnold dir was misssing, it is building now.

The testsuite with python 2.7 has this error:
```
scons: *** [build/darwin_x86_64/gcc_debug/usd-0.22.11_arnold-7.2.1.0.beta50/testsuite/index.html] UnicodeEncodeError : 'ascii' codec can't encode character u'\xee' in position 276673: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/picharc/develop/ansono/arnold-usd/tools/scons/scons-local-3.1.2/SCons/Action.py", line 1209, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/Users/picharc/develop/ansono/arnold-usd/testsuite/SConscript", line 549, in process_testsuite
    report_file.write(SimpleTemplate(template_file.read()).render(report_params))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 276673: ordinal not in range(128)
```
The build with python3.10 has this error:
```
  File "/Users/picharc/develop/ansono/arnold-usd/tools/scons/scons-local-3.1.2/SCons/Action.py", line 1209, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/Users/picharc/develop/ansono/arnold-usd/tools/utils/configure.py", line 34, in configure_plug_info
    import system
ModuleNotFoundError: No module named 'system'
```
I am not sure why, would you have an idea ?

**Comment by cpichard** [comment]
Hi @ansono ,
I am running abuild with python3.10 and the testsuite seem to work except it is picking up the procedural coming with the api. It looks like it didn't compile with arm64 on mac m1. Is it something I can fix in the custom.py ?
Here is an excerpt of one of the test showing it is not picking up the compiled procedural
`00:00:00    88MB WARNING |  unable to load dynamic library: dlopen(/Users/picharc/develop/ansono/arnold-usd/build/darwin_x86_64/gcc_debug/usd-0.22.11_arnold-7.2.1.0.beta50/procedural/usd_proc.dylib, 0x0005): tried: '/Users/picharc/installs/usd-22.11/bin/usd_proc.dylib' (no such file), '/Users/picharc/installs/Arnold-7.2.1.0.beta50_20230310010907_2d076d4e_darwin_18.1/bin/usd_proc.dylib' (no such file), '/Users/picharc/installs/usd-22.11/lib/usd_proc.dylib' (no such file), '/Users/picharc/develop/ansono/arnold-usd/build/darwin_x86_64/gcc_debug/usd-0.22.11_arnold-7.2.1.0.beta50/procedural/usd_proc.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

I don't have this issue when I use python2.7 for abuild.

**Pull request merged**
